# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Куликов Максим Александрович
- ИВТ-22-1

| Задание    | Лаб_раб | Сам_раб |
|------------|---------| ------ |
| Задание 1  | +       | + |
| Задание 2  | +       | + |
| Задание 3  | +       |  +|
| Задание 4  | +       |  +|
| Задание 5  | +       |  +|

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа 10
## Задание №1
### Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто “возьмёт их из этого декоратора”). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи.P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания.
```python
from functools import lru_cache

@lru_cache(None)
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)

if __name__ == '__main__':
    print(fibonacci(100))
```
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/lab10_1.png)
## Вывод
В этом задании я изучил применение декоратора @lru_cache для оптимизации вычисления чисел Фибоначчи. 

## Задание №2
### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130.Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.
```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name, age)
    return output_func

@check
def personal_info(name, age):
    print(f"Name: {name}, Age: {age}")

if __name__ == '__main__':
    personal_info('Владимир', 38)
    personal_info('Александр', -5)
    personal_info('Петр', 138, 15, 48, 2)
```
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/lab10_2.png)
## Вывод
В этом задании я изучил создание декоратора для проверки корректности входных данных.

## Задание №3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт.Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.
```python
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')

if __name__ == '__main__':
    data([1, 15, 'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])
```
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/lab10_3.png)
## Вывод
В этом задании я изучил обработку исключений для защиты функции от неверных типов данных. 

## Задание №4
### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десятисимволов, а если имя имеет допустимую длину, то в консоль выводиться “Успешная регистрация”
```python
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name) > 10:
        raise NegativeValueException('Длина более 10 символов')
    else:
        print('Успешная регистрация')

if __name__ == '__main__':
    name = '12345678910'
    check_name(name)
```
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/lab10_4.png)
## Вывод
В этом задании я изучил создание пользовательского исключения для проверки длины имени при регистрации. Если длина строки превышает 10 символов, выбрасывается исключение NegativeValueException. 

## Задание №5
### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: __init__() (вызывается при создании класса декоратора в программе) и __call__() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.
```python
class SiteChecker:
    def __init__(self, func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('> Проверка перед запуском', self.func.__name__)
        self.func()
        print('> Проверка безопасного выключения')

@SiteChecker
def site():
    print('Успешная работа сайта')

if __name__ == '__main__':
    print('>> Сайт запущен')
    site()
    print('>> Сайт выключен')
```
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/lab10_5.png)
## Вывод
В этом задании я изучил создание простого логгера с помощью класса-декоратора. Метод __init__() инициализирует декоратор, а метод __call__() выводит логи до и после выполнения функции.


## Самостоятельная работа 10
## Задание №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.
### Подсказка: необходимо использовать модуль time
### Декоратор необходимо использовать для этой функции:
```python
import time

def time_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()  
        result = func(*args, **kwargs)
        end_time = time.time() 
        execution_time = end_time - start_time  
        print(f"\nВремя выполнения: {execution_time:.5f} секунд")
        return result
    return wrapper

@time_decorator
def fibonacci():
    fib1 = fib2 = 1

    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/sam10_1.png)
## Вывод
В этом задании я изучил создание декоратора для измерения времени выполнения функции. Декоратор time_decorator использует модуль time для определения времени начала и конца выполнения функции, после чего выводит общее время исполнения.

## Задание №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. 
### После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.
```python
def read_file(file_path):
    try:
        with open(file_path, 'r') as file:
            content = file.read()
            if not content: 
                raise ValueError("файл пустой")
            print(content)
    except ValueError as e:
        print(e)
    except FileNotFoundError:
        print(f"Файл '{file_path}' не найден")

if __name__ == '__main__':
    read_file('empty_file.txt')
    read_file('info_file.txt')
```
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/sam10_2.png)
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/sam10_2_empty.png)
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/sam10_2_info.png)
## Вывод
В этом задании я изучил обработку исключений при чтении данных из файлов. 

## Задание №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль
```python
def add_two(user_input):
    try:
        number = float(user_input)
        result = 2 + number
        print(f"Результат: {result}")
    except ValueError:  
        print("Неподходящий тип данных. Ожидалось число.")
    except TypeError: 
        print("Неподходящий тип данных. Ожидалось число.")

if __name__ == '__main__':
    add_two(5)      
    add_two("10.5") 
    add_two("abc")  
    add_two([1, 2]) 
```
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/sam10_3.png)
## Вывод
В этом задании я изучил обработку исключений при сложении числа с введённым пользователем значением.

## Задание №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.
```python
class FunctionCallTracker:
    def __init__(self, func):
        self.func = func
        self.calls = {}  

    def __call__(self, *args, **kwargs):
        if self.func.__name__ in self.calls:
            print(f"Функция '{self.func.__name__}' уже была вызвана ранее.")
        else:
            print(f"Функция '{self.func.__name__}' вызывается впервые.")
        
        self.calls[self.func.__name__] = self.calls.get(self.func.__name__, 0) + 1
        
        return self.func(*args, **kwargs)
# Первая функция: сложение двух чисел
@FunctionCallTracker
def add(a, b):
    result = a + b
    print(f"Результат сложения: {result}")
    return result
# Вторая функция: умножение двух чисел
@FunctionCallTracker
def multiply(a, b):
    result = a * b
    print(f"Результат умножения: {result}")
    return result

if __name__ == '__main__':
    add(3, 5)       
    add(2, 4)       
    multiply(2, 3)   
    multiply(5, 6) 
```
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/sam10_4_1.png)
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/sam10_4_2.png)
## Вывод
В этом задании я создал собственный декоратор FunctionCallTracker, который отслеживает количество вызовов функций.

## Задание №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.
```python
class ValueOutOfRangeError(Exception):
    def __init__(self, message="Значение вышло за допустимые границы"):
        self.message = message
        super().__init__(self.message)

# Первая функция: проверка числа
def check_number(number, min_value, max_value):
    if number < min_value or number > max_value:
        raise ValueOutOfRangeError(f"Число {number} вне допустимого диапазона ({min_value}, {max_value})")
    else:
        print(f"Число {number} в допустимых пределах.")

# Вторая функция: проверка длины строки
def check_string(string, max_length):
    if len(string) > max_length:
        raise ValueOutOfRangeError(f"Длина строки превышает {max_length} символов")
    else:
        print(f"Длина строки в пределах {max_length} символов.")

if __name__ == '__main__':
    try:
        check_number(10, 1, 5)  
    except ValueOutOfRangeError as e:
        print(e)

    try:
        check_number(3, 1, 5)   
    except ValueOutOfRangeError as e:
        print(e)

    try:
        check_string("Привет", 3) 
    except ValueOutOfRangeError as e:
        print(e)

    try:
        check_string("Привет", 10) 
    except ValueOutOfRangeError as e:
        print(e)
```
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/sam10_5_1.png)
### ![Результат](https://github.com/RahaMilopNo/Software_Engineering/blob/Tema_10/theme_10/screen/sam10_5_2.png)
## Вывод
В этом задании я создал собственное исключение ValueOutOfRangeError, которое используется для проверки значений на выход за пределы допустимого диапазона.

## Общие выводы по теме
В ходе изучения декораторов и исключений в Python я осознал их важность для улучшения структуры и надежности кода. 
